import { fmt } from "./utils";

/**
 * Downloads an array of objects as a CSV file.
 * @param {object[]} data     - Array of row objects
 * @param {string}   filename - e.g. "salary-plan.csv"
 */
export function exportCSV(data, filename) {
  if (!data.length) return;
  const keys = Object.keys(data[0]);
  const csv  = [
    keys.join(","),
    ...data.map(r => keys.map(k => `"${r[k]}"`).join(",")),
  ].join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
}

/**
 * Downloads a simulation result as a formatted text report.
 * @param {object} simResult - Result object from runMonteCarlo()
 * @param {string} simName   - Simulation name
 * @param {string} aiSummary - AI-generated summary text (optional)
 */
export function exportSimPDF(simResult, simName, aiSummary) {
  const content = `FINTECH.AI — SIMULATION REPORT
================================
Simulation: ${simName}
Generated:  ${new Date().toLocaleDateString("en-IN")}

SCENARIO OUTCOMES (Monte Carlo N=200)
─────────────────────────────────────
P10 (Pessimistic)  Runway: ${simResult.p10.runway} mo  Final Cash: ${fmt(simResult.p10.finalCash)}
P50 (Base Case)    Runway: ${simResult.p50.runway} mo  Final Cash: ${fmt(simResult.p50.finalCash)}
P90 (Optimistic)   Runway: ${simResult.p90.runway} mo  Final Cash: ${fmt(simResult.p90.finalCash)}

Survival Rate: ${simResult.survivalRate}%
Avg Runway:    ${simResult.avgRunway} months

AI CFO SUMMARY
──────────────
${aiSummary || "Not generated."}

Monthly Projections (Base Case)
────────────────────────────────
${simResult.chartData
  .map(d => `${d.month}: Revenue ${fmt(d.revenue)} | Burn ${fmt(d.burn)} | Cash ${fmt(d.p50)}`)
  .join("\n")}

─────────────────────────────────────────────────────────────
Generated by fintech.ai — AI-Powered CFO Assistant
`;
  const blob = new Blob([content], { type: "text/plain" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${simName.replace(/\s+/g, "-")}-report.txt`;
  a.click();
}
